version: "3"
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.static
    ports:
      - 6006:6006
  nginx-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 9099:80
  nginx-app-simple:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 9099:80
  learn-nginx:
    image: nginx:alpine
    ports:
      - 9099:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html